name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stable-slim
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: apt-get update && apt-get install -y curl unzip git

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bunx tsc -p .
